import Head from 'next/head';

import { Workspace } from '@blocksuite/store';
import { createEvent } from "@blocksuite/blocks/std";
// import "@blocksuite/editor";
// import "@blocksuite/blocks/style";
// import { createEditor, createDebugMenu, BlockSchema } from "@blocksuite/editor";
// import { Workspace, Page } from "@blocksuite/store";

console.log(new Workspace({}));

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => {
        window.dispatchEvent(
          createEvent('affine.switch-mouse-mode', {
            type: 'default'
          })
        )
      }}>

      </button>
    </>
  );
}
