name: Nightly Release Build Test

on:
  schedule:
    # At 00:05 of everyday
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  nightly-build-test:
    name: Nightly Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Install Nightly Version
        run: |
          pnpm install @blocksuite/blocks@nightly
          pnpm install @blocksuite/editor@nightly
          pnpm install @blocksuite/store@nightly

      - name: Build Next.js
        run: pnpm run build